In [23]:
import numpy as np
import pandas as pd
from pathlib import Path
import PIL
import glob
from matplotlib import image
import matplotlib.pyplot as plt

In [63]:
classes = Path("PersianLPR/").glob('*')

In [64]:
X = []
y = []

In [65]:
for class_path in classes:
    for image_path in class_path.glob("*"):
        image_file = image.imread(image_path)
        y.append('ุณ' if class_path.name == "S" else 'ุต' if class_path.name == "W" else class_path.name)
        X.append(image_file.reshape(image_file.size))
X = np.array(X)
y = np.array(y)

In [66]:
X.shape

(1500, 256)

In [72]:
y.shape

(1500,)

In [74]:
columns = {f'pixel{i}': X[:, i] for i in range(y.size}
columns

TypeError: 'int' object is not callable

In [77]:
df = pd.DataFrame({'target': y, **{f'pixel{i}': X[:, i] for i in range(X.shape[1])}})
df.head()

,target,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel246,pixel247,pixel248,pixel249,pixel250,pixel251,pixel252,pixel253,pixel254,pixel255
0,2,86,89,86,80,80,83,80,74,77,...,100,109,97,77,63,52,40,34,40,57
1,2,109,117,124,136,141,138,129,121,110,...,75,82,75,58,34,22,14,7,8,12
2,2,84,84,90,93,90,81,72,84,96,...,90,84,75,61,52,52,55,58,61,55
3,2,69,72,75,73,69,64,61,61,61,...,109,116,116,114,111,105,97,97,94,90
4,2,78,81,75,70,61,49,38,26,26,...,113,119,116,107,99,87,78,72,70,67

In [78]:
df.shape

(1500, 257)

In [85]:
df.to_csv('PersianLPR.csv', index=False)

In [80]:
df[df.target == 'ุต'].head()

,target,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel246,pixel247,pixel248,pixel249,pixel250,pixel251,pixel252,pixel253,pixel254,pixel255
1200,ุต,51,45,38,26,22,35,57,70,61,...,105,45,16,13,16,26,29,26,26,26
1201,ุต,27,24,15,12,15,20,26,30,29,...,56,15,2,0,0,0,0,0,0,0
1202,ุต,60,56,56,63,61,65,82,91,71,...,86,48,37,45,48,48,48,50,50,48
1203,ุต,0,0,2,5,5,7,16,35,40,...,83,35,7,0,0,0,0,0,0,0
1204,ุต,16,13,11,11,16,16,19,32,30,...,118,43,13,5,5,5,5,8,11,11

In [81]:
data = pd.read_csv('PersianLPR.csv')
data.head()

,target,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel246,pixel247,pixel248,pixel249,pixel250,pixel251,pixel252,pixel253,pixel254,pixel255
0,2,86,89,86,80,80,83,80,74,77,...,100,109,97,77,63,52,40,34,40,57
1,2,109,117,124,136,141,138,129,121,110,...,75,82,75,58,34,22,14,7,8,12
2,2,84,84,90,93,90,81,72,84,96,...,90,84,75,61,52,52,55,58,61,55
3,2,69,72,75,73,69,64,61,61,61,...,109,116,116,114,111,105,97,97,94,90
4,2,78,81,75,70,61,49,38,26,26,...,113,119,116,107,99,87,78,72,70,67

In [82]:
from sklearn.utils import shuffle

In [83]:
df = shuffle(df)

In [84]:
df.head()

,target,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel246,pixel247,pixel248,pixel249,pixel250,pixel251,pixel252,pixel253,pixel254,pixel255
287,2,69,80,90,92,84,69,57,49,47,...,139,135,116,86,55,39,35,39,45,49
165,2,78,92,120,135,92,50,0,28,71,...,78,85,85,78,64,57,50,57,57,85
832,7,45,45,62,69,50,25,12,7,5,...,69,79,84,79,62,52,50,52,47,45
327,3,117,120,123,122,118,117,117,120,118,...,90,72,33,5,0,2,12,15,13,17
1326,ุต,19,17,10,17,29,24,29,36,27,...,80,49,27,22,15,17,17,17,15,12